###############################################
# Kubernetes Secret for DB Credentials + JWT
###############################################

apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
data:
  DB_HOST: {{ .Values.db.host | b64enc }}
  DB_NAME: {{ .Values.db.name | b64enc }}
  DB_USER: {{ .Values.db.user | b64enc }}
  DB_PASSWORD: {{ .Values.db.password | b64enc }}
  JWT_SECRET: {{ .Values.jwtSecret | b64enc }}
