apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/<YOUR_GITHUB_USERNAME>/ecommerce-devops-project.git"
    targetRevision: main
    path: helm-charts/orders
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
